groups:
- name: main
  jobs:
  - deploy-app
  #- load-tests
  #- promote-new-version
  
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest
    
resources:
- name: blue-green-deployment-pipeline
  type: git
  source:
    uri: https://github.com/dunc101/concourse-cf-blue-green.git
    
- name: resource-deploy-blue-green
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}
    
# nexus repo for SNAPSHOTS. 
- name: artifact
  type: maven-resource
  source:
    url: http://maven01.ipacc.com:8081/nexus/content/repositories/infinity-releases
    artifact: ((nexus-artifact-name))
    username: ((nexus-username))
    password: ((nexus-password))
    
jobs:
- name: deploy-app
  serial: true
  public: true
  plan:
  - get: blue-green-deployment-pipeline
  - task: get-current-app-color
    file: blue-green-deployment-pipeline/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: prepare-app-manifest
    file: blue-green-deployment-pipeline/tasks/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
  - get: artifact
  - put: resource-deploy-blue-green
    params:
      manifest: app-manifest-output/manifest.yml
      path: artifact/*.jar

#- name: load-tests
#  serial: true
#  public: true
#  plan:
#  - get: concourse-pipeline-samples
#    trigger: true
#    passed:
#      - deploy-app
#  - task: get-current-app-color
#    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/current-app-get-info.yml
#    params:
#      PWS_APP_SUFFIX: {{pws-app-suffix}}
#      PWS_API: {{pws-api}}
#      PWS_ORG: {{pws-organization}}#
#      PWS_USER: {{deploy-username}}
#      PWS_PWD: {{deploy-password}}#
#      PWS_SPACE: {{pws-space}}
#  - task: run-load-tests#
#    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/load-tests.yml
#    params:#
#      PWS_APP_SUFFIX: {{pws-app-suffix}}
#      PWS_APP_DOMAIN: {{pws-app-domain}}#
#
#- name: promote-new-version#
#  serial: true
#  public: true#
#  plan:
#  - get: concourse-pipeline-samples#
#    trigger: true
#    passed:#
#      - load-tests
#  - task: get-current-app-color#
#    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/current-app-get-info.yml
#    params:#
#      PWS_APP_SUFFIX: {{pws-app-suffix}}
#      PWS_API: {{pws-api}}#
#      PWS_ORG: {{pws-organization}}
#      PWS_USER: {{deploy-username}}#
#      PWS_PWD: {{deploy-password}}
#      PWS_SPACE: {{pws-space}}#
#  - task: switch-app-routes
#    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/update-routes.yml#
#    params:
#      PWS_APP_SUFFIX: {{pws-app-suffix}}#
#      PWS_APP_DOMAIN: {{pws-app-domain}}
#      PWS_API: {{pws-api}}#
#      PWS_ORG: {{pws-organization}}
#      PWS_USER: {{deploy-username}}#
#      PWS_PWD: {{deploy-password}}
#      PWS_SPACE: {{pws-space}}#
##