---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: blue-green-deployment-pipeline
- name: current-app-info

outputs:
- name: app-manifest-output

run:
  path: blue-green-deployment-pipeline/tasks/app-manifest-prep
