---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: blue-green-deployment-pipeline

outputs:
- name: current-app-info

run:
  path: blue-green-deployment-pipeline/tasks/current-app-get-info
