#!/bin/bash

set -e

echo "Verifying deployment ..."

export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export NEXT_APP_URL=http://$NEXT_APP_COLOR-$PWS_APP_SUFFIX.$PWS_APP_DOMAIN/

echo "Performing deployment smoke tests!"

mvn test -DserverUrl=$NEXT_APP_URL
