---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: blue-green-deployment-pipeline
- name: current-app-info

run:
  path: blue-green-deployment-pipeline/tasks/update-routes
