---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: blue-green-deployment-pipeline
- name: current-app-info

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x blue-green-deployment-pipeline/tasks/update-routes
    sh blue-green-deployment-pipeline/tasks/update-routes
